# create your drupal and postgres config here, based off the last assignment
version: '3'

services:
  drupal:
    image: drupal:latest # this will use the latest version
    ports:
      - '8080:80' # expose 80 on host and sent to 80 in container
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
  postgres:
    image: postgres
    environment: 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=drupal

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: